-- MySQL Script generated by MySQL Workbench
-- Wed Jun 11 16:12:07 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema escambo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escambo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escambo` ;
USE `escambo` ;

-- -----------------------------------------------------
-- Table `escambo`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escambo`.`livro` (
  `livro_id` INT NOT NULL AUTO_INCREMENT,
  `livro_titulo` VARCHAR(255) NOT NULL,
  `livro_autor` VARCHAR(255) NOT NULL,
  `livro_genero` VARCHAR(255) NOT NULL,
  `foto1_livro` VARCHAR(200) NOT NULL,
  `foto2_livro` VARCHAR(200) NOT NULL,
  `livro_descricao` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`livro_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escambo`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escambo`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `usuario_nome` VARCHAR(255) NOT NULL,
  `usuario_email` VARCHAR(255) NOT NULL,
  `usuario_senha` VARCHAR(255) NOT NULL,
  `usuario_endereco` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `usuario_email_UNIQUE` (`usuario_email` ASC) VISIBLE,
  UNIQUE INDEX `usuario_senha_UNIQUE` (`usuario_senha` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escambo`.`troca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escambo`.`troca` (
  `troca_id` INT NOT NULL AUTO_INCREMENT,
  `troca_data` DATE NOT NULL,
  `troca_status` VARCHAR(255) NOT NULL,
  `usuario_id_proponente` INT NOT NULL,
  `usuario_id_destinatario` INT NOT NULL,
  `livro_livro_id_desejado` INT NOT NULL,
  `livro_livro_oferecido` INT NOT NULL,
  PRIMARY KEY (`troca_id`),
  INDEX `fk_troca_usuario_idx` (`usuario_id_proponente` ASC) VISIBLE,
  INDEX `fk_troca_usuario1_idx` (`usuario_id_destinatario` ASC) VISIBLE,
  INDEX `fk_troca_livro1_idx` (`livro_livro_id_desejado` ASC) VISIBLE,
  INDEX `fk_troca_livro2_idx` (`livro_livro_oferecido` ASC) VISIBLE,
  CONSTRAINT `fk_troca_usuario`
    FOREIGN KEY (`usuario_id_proponente`)
    REFERENCES `escambo`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_troca_usuario1`
    FOREIGN KEY (`usuario_id_destinatario`)
    REFERENCES `escambo`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_troca_livro1`
    FOREIGN KEY (`livro_livro_id_desejado`)
    REFERENCES `escambo`.`livro` (`livro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_troca_livro2`
    FOREIGN KEY (`livro_livro_oferecido`)
    REFERENCES `escambo`.`livro` (`livro_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
INSERT INTO `livro` (`livro_titulo`, `livro_autor`, `livro_genero`, `foto1_livro`, `foto2_livro`, `livro_descricao`) VALUES
('O Pequeno Príncipe', 'Antoine de Saint-Exupéry', 'Ficção', 'pequeno1.jpg', 'pequeno2.jpg', 'Uma fábula sobre amor e amizade.'),
('Dom Casmurro', 'Machado de Assis', 'Romance', 'casmurro1.jpg', 'casmurro2.jpg', 'Clássico da literatura brasileira.'),
('1984', 'George Orwell', 'Distopia', '1984a.jpg', '1984b.jpg', 'Uma crítica ao totalitarismo.'),
('Harry Potter e a Pedra Filosofal', 'J.K. Rowling', 'Fantasia', 'hp1.jpg', 'hp2.jpg', 'O início da jornada de Harry.'),
('A Arte da Guerra', 'Sun Tzu', 'Estratégia', 'guerra1.jpg', 'guerra2.jpg', 'Princípios estratégicos milenares.');
INSERT INTO `usuario` (`usuario_nome`, `usuario_email`, `usuario_senha`, `usuario_endereco`) VALUES
('Ana Silva', 'ana@email.com', 'senha123', 'Rua das Flores, 100'),
('Carlos Souza', 'carlos@email.com', 'abc12345', 'Av. Central, 200'),
('Juliana Lima', 'juliana@email.com', 'juliana2025', 'Rua do Sol, 321'),
('Marcos Paulo', 'marcos@email.com', 'marcosp!', 'Rua A, 999'),
('Lúcia Torres', 'lucia@email.com', 'lucia456', 'Av. das Palmeiras, 88');
